config/routes.rb
Rails.application.routes.draw do
  resources :votes
  root 'stories#index'
  devise_for :users
  resources :users do
    resources :stories, :controller=>"user_stories"
    resources :sentences, :controller=>"user_contributions"
  end
  resources :stories do
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    get '/starter' => 'sentences#starter', as: :starter
    get '/description' => 'stories#description', as: :description
    resources :sentences do
      post '/up-vote' => 'votes#up_vote', as: :up_vote
      post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
  end
  resources :sentences
end

app/models/sentence.rb
class Sentence < ApplicationRecord
  belongs_to :story
  belongs_to :user
  validates :content, :presence => true
  has_many :votes, as: :voteable, dependent: :destroy

  def up_votes
    votes.where(value: 1).count
  end
  def down_votes
    votes.where(value: -1).count
  end
  def points
    self.votes.sum(:value)
  end
  def update_rank
    new_rank = self.points
    story=self.story
    self.update_attribute(:rank, new_rank)
    if new_rank > 0
      self.update_attribute(:confirmed, true)
      sentences = story.sentences
      sentences.each do |sentence|
        if sentence.confirmed == nil
          sentence.update_attribute(:confirmed, false)
        end
      end
    end
  end
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController
  before_filter :authenticate_user!, except: [:index, :show]
  before_action :set_sentence, only: [:show, :edit, :update, :destroy]

  # GET /sentences
  # GET /sentences.json
  def index
    @sentences = Sentence.all
  end

  # GET /sentences/1
  # GET /sentences/1.json
  def show
  end

  # GET /sentences/new
  def new
    @story=Story.find(params[:story_id])
    @sentence = Sentence.new
    @random=rand(10)
    @user = current_user.id
    @confirmed=@story.sentences.where(:confirmed => true).order('updated_at')
  end

  # GET /sentences/1/edit
  def edit
  end

  # POST /sentences
  # POST /sentences.json
  def create
    @sentence = Sentence.new(sentence_params)
    @story = Story.find(params[:story_id])

    respond_to do |format|
      if @sentence.save
        start = @story.sentences.first
        start.confirmed=true
        start.save
        format.html { redirect_to @story, notice: 'Sentence was successfully created.' }
        format.json { render :show, status: :created, location: @sentence }
      else
        format.html { render :new }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sentences/1
  # PATCH/PUT /sentences/1.json
  def update
    respond_to do |format|
      if @sentence.update(sentence_params)
        format.html { redirect_to @sentence, notice: 'Sentence was successfully updated.' }
        format.json { render :show, status: :ok, location: @sentence }
      else
        format.html { render :edit }
        format.json { render json: @sentence.errors, status: :unprocessable_entity }
      end
    end
  end

  def starter
    @story=Story.find(params[:story_id])
    @sentence=Sentence.new
    @user=current_user.id
  end

  # DELETE /sentences/1
  # DELETE /sentences/1.json
  def destroy
    @sentence.destroy
    respond_to do |format|
      format.html { redirect_to sentences_url, notice: 'Sentence was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sentence
      @sentence = Sentence.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sentence_params
      params.require(:sentence).permit(:content, :user_id, :story_id, :image)
    end
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/sentences/_form.html.erb
<%= form_for [@story, sentence] do |f| %>
  <% if sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
      <% sentence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control contribution"%>
  </div>

  <%= f.hidden_field :story_id, :value => @story.id %>

  <%= f.hidden_field :user_id, :value => @user %>


  <div class="actions">
    <%= f.submit "Submit Contribution", :class => "btn"%>
  </div>
<% end %>

app/views/sentences/_starter-form.erb
<%= form_for [@story, sentence] do |f| %>
  <% if sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
      <% sentence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :content %>
    <%= f.text_area :content, :class => "form-control contribution"%>
  </div>

  <%= f.hidden_field :story_id, :value => @story.id %>

  <%= f.hidden_field :user_id, :value => @user %>


  <div class="actions">
    <%= f.submit "Open book to public", :class => "btn"%>
  </div>
<% end %>

app/views/sentences/edit.html.erb
<h1>Editing Sentence</h1>

<%= form_for [@sentence] do |f| %>
  <% if @sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sentence.errors.count, "error") %> prohibited this sentence from being saved:</h2>

      <ul>
      <% @sentence.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %>
    <%= f.text_field :content %>
  </div>

  <%= f.hidden_field :story_id, :value => @sentence.story.id %>

  <%= f.hidden_field :user_id, :value => @sentence.user.id %>

  <%= f.hidden_field :image, :value => @sentence.image %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<%= link_to 'Show', @sentence %> |
<%= link_to 'Back', sentences_path %>

app/views/sentences/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sentences</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sentences.each do |sentence| %>
      <tr>
        <td><%= sentence.content %></td>
        <td><%= sentence.user_id %></td>
        <td><%= link_to 'Show', sentence %></td>
        <td><%= link_to 'Edit', edit_sentence_path(sentence) %></td>
        <td><%= link_to 'Destroy', sentence, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sentence', new_sentence_path %>

app/views/sentences/new.html.erb
<h1>New Sentence</h1>
<div class="container">
  <h1 class="book-title title"><%= @story.name %></h1>
  <h4 class="book-author"><%= @story.user.email %></h4>
  <%= link_to 'Back', stories_path, class: "btn btn-primary back"%>
  <div class="story-content col-xs-12">
    <% if @confirmed %>
      <% @confirmed.each do |sentence| %>
        <div class="row">
          <div class="col-xs-10">
            <%= sentence.content%>
          </div>
          <div class="col-xs-1">
            <%= image_tag(current_user.avatar.url(:thumb), :class=>"user-image")%>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<%= render 'form', sentence: @sentence %>

app/views/sentences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @sentence.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @sentence.user_id %>
</p>

<%= image_tag ("xkcd/#{@sentence.image}"), class: "story-image"%>

<%= link_to 'Edit', edit_sentence_path(@sentence) %> |
<%= link_to 'Back', sentences_path %>

app/views/sentences/starter.html.erb
<h1>Start writing your book before you publish it for others to contribute</h1>
<div class="container">
  <h1 class="book-title title"><%= @story.name %></h1>
  <h4 class="book-author"><%= @story.user.email %></h4>
  <%= link_to 'Back', stories_path, class: "btn btn-primary back"%>
</div>
<%= render 'starter-form', sentence: @sentence %>