config/routes.rb
Rails.application.routes.draw do
  resources :votes
  root 'stories#index'
  devise_for :users
  resources :users do
    resources :stories, :controller=>"user_stories"
    resources :sentences, :controller=>"user_contributions"
  end
  resources :stories do
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    get '/starter' => 'sentences#starter', as: :starter
    get '/description' => 'stories#description', as: :description
    resources :sentences do
      post '/up-vote' => 'votes#up_vote', as: :up_vote
      post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
  end
  resources :sentences
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :voteable, polymorphic: true
  after_save :update_voteable

  private
  def update_voteable
    voteable.update_rank
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_action :set_vote, only: [:show, :edit, :update, :destroy]

  # GET /votes
  # GET /votes.json
  def index
    @votes = Vote.all
  end

  # GET /votes/1
  # GET /votes/1.json
  def show
  end

  # GET /votes/new
  def new
    @vote = Vote.new
  end

  # GET /votes/1/edit
  def edit
  end

  # POST /votes
  # POST /votes.json
  def create
    @vote = Vote.new(vote_params)

    respond_to do |format|
      if @vote.save
        format.html { redirect_to @vote, notice: 'Vote was successfully created.' }
        format.json { render :show, status: :created, location: @vote }
      else
        format.html { render :new }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /votes/1
  # PATCH/PUT /votes/1.json
  def update
    respond_to do |format|
      if @vote.update(vote_params)
        format.html { redirect_to @vote, notice: 'Vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @vote }
      else
        format.html { render :edit }
        format.json { render json: @vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /votes/1
  # DELETE /votes/1.json
  def destroy
    @vote.destroy
    respond_to do |format|
      format.html { redirect_to votes_url, notice: 'Vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def up_vote
    update_vote(1)
    redirect_to :back
  end

  def down_vote
    update_vote(-1)
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vote
      @vote = Vote.find(params[:id])
    end

    def update_vote(new_value)
    @sentence = Sentence.find(params[:sentence_id]) if params[:sentence_id] else nil
    @story = Story.find(params[:story_id])
    votable = @sentence if @sentence
    votable = @story if @story && @sentence==nil

    @vote = votable.votes.where(user_id: current_user.id).first

    if @vote
      @vote.update_attribute(:value, new_value)
    else
      @vote = current_user.votes.create(value: new_value, voteable: votable)
    end

  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vote_params
      params.require(:vote).permit(:value, :user_id, :voteable_id, :voteable_type)
    end
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/votes/_form.html.erb
<%= form_for(vote) do |f| %>
  <% if vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %>
    <%= f.number_field :value %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :voteable_id %>
    <%= f.number_field :voteable_id %>
  </div>

  <div class="field">
    <%= f.label :voteable_type %>
    <%= f.text_field :voteable_type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/votes/_storyvoter.html.erb
<div class="text-center col-xs-1 voter">
  <% if current_user %>
    <div class="width: 100%"><%= link_to " ", story_up_vote_path(story), class: 'glyphicon glyphicon-chevron-up', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
  <% else %>
    <div class="width: 100%"><%= link_to " ", new_user_session_path, class: 'glyphicon glyphicon-chevron-up', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
  <% end %>
  <div class="width: 100%"><h3 style="margin-top: 0; margin-bottom: 0;"><strong><%= story.points %></strong></h3></div>
  <% if current_user %>
    <div class="width: 100%"><%= link_to " ", story_down_vote_path(story), class: 'glyphicon glyphicon-chevron-down', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
  <% else %>
    <div class="width: 100%"><%= link_to " ", new_user_session_path, class: 'glyphicon glyphicon-chevron-down', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
  <% end %>
</div>

app/views/votes/_voter.html.erb
<div class="text-center col-xs-1">
  <% if sentence.confirmed %>
    <div class="width: 100%"><h5 style="margin-top: 0; margin-bottom: 0"><strong>Confirmed</strong></h5></div>
  <% else %>
    <% if current_user %>
      <div class="width: 100%"><%= link_to " ", story_sentence_up_vote_path(story, sentence), class: 'glyphicon glyphicon-chevron-up', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
    <% else %>
      <div class="width: 100%"><%= link_to " ", new_user_session_path, class: 'glyphicon glyphicon-chevron-up', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
    <% end %>
    <div class="width: 100%"><h3 style="margin-top: 0; margin-bottom: 0"><strong><%= sentence.points%></strong></h3></div>
    <% if current_user %>
      <div class="width: 100%"><%= link_to " ", story_sentence_down_vote_path(story, sentence), class: 'glyphicon glyphicon-chevron-down', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
    <% else %>
      <div class="width: 100%"><%= link_to " ", new_user_session_path, class: 'glyphicon glyphicon-chevron-down', method: :post, style: "margin-right: 0; margin-left: 0" %></div>
    <% end %>
  <% end %>
</div>

app/views/votes/edit.html.erb
<h1>Editing Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

app/views/votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Votes</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>User</th>
      <th>Voteable</th>
      <th>Voteable type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @votes.each do |vote| %>
      <tr>
        <td><%= vote.value %></td>
        <td><%= vote.user_id %></td>
        <td><%= vote.voteable_id %></td>
        <td><%= vote.voteable_type %></td>
        <td><%= link_to 'Show', vote %></td>
        <td><%= link_to 'Edit', edit_vote_path(vote) %></td>
        <td><%= link_to 'Destroy', vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vote', new_vote_path %>

app/views/votes/new.html.erb
<h1>New Vote</h1>

<%= render 'form', vote: @vote %>

<%= link_to 'Back', votes_path %>

app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @vote.value %>
</p>

<p>
  <strong>User:</strong>
  <%= @vote.user_id %>
</p>

<p>
  <strong>Voteable:</strong>
  <%= @vote.voteable_id %>
</p>

<p>
  <strong>Voteable type:</strong>
  <%= @vote.voteable_type %>
</p>

<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>