config/routes.rb
Rails.application.routes.draw do
  resources :votes
  root 'stories#index'
  devise_for :users
  resources :users do
    resources :stories, :controller=>"user_stories"
    resources :sentences, :controller=>"user_contributions"
  end
  resources :stories do
    post '/up-vote' => 'votes#up_vote', as: :up_vote
    post '/down-vote' => 'votes#down_vote', as: :down_vote
    get '/starter' => 'sentences#starter', as: :starter
    get '/description' => 'stories#description', as: :description
    resources :sentences do
      post '/up-vote' => 'votes#up_vote', as: :up_vote
      post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
  end
  resources :sentences
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>

    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Cedarville+Cursive" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tag %>
  </head>

  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li><%= link_to 'All Books', stories_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'My Books', user_stories_path(current_user) %></li>
              <li><%= link_to 'My Contributions', user_sentences_path(current_user) %></li>
            <%end%>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <div class="dropdown">
                <button class="dropdown-toggle round-image-50" type="button" data-toggle="dropdown"><%= image_tag(current_user.avatar.url(:thumb)) %>
                <span class="caret"></span></button>
                <ul class="dropdown-menu">
                  <li><%= link_to 'Edit profile', edit_user_registration_path %></li>
                  <li><%= link_to 'Logout', destroy_user_session_path, method: :delete%></li>
                </ul>
              </div>
            <% else %>
              <li><%= link_to "Sign up", new_user_registration_path %></li>
              <li><%= link_to "Login", new_user_session_path %></li>
            <% end%>
          </ul>
        </div>
      </div>
    </nav>
    <% flash.each do |name, msg|%>
      <%= content_tag :div, msg, id: "flash_#{name}"%>
    <%end%>
    <%= yield %>
  </body>
</html>